# Generated by Django 5.1 on 2024-08-30 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_leçon_chapitre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cours/images/'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='auteur',
            field=models.ForeignKey(limit_choices_to={'role': 'administrateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to=settings.AUTH_USER_MODEL),
        ),
    ]
