# Generated by Django 5.1 on 2024-08-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_rename_image_cours_cours_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='cours_status',
            field=models.CharField(choices=[('active', 'Démarré'), ('inactive', 'Pas encore commencé')], default='inactive', max_length=25),
        ),
    ]
