# Generated by Django 5.1 on 2024-09-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_coursutilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catégorie',
            old_name='libellé',
            new_name='name',
        ),
    ]
