# Generated by Django 5.1 on 2024-09-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_rename_libellé_catégorie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catégorie',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
