# Generated by Django 5.1 on 2024-09-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0010_cours_average_rating_cours_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='titre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
