# Generated by Django 5.1 on 2024-09-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_alter_cours_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='catégorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='durée',
            new_name='duree',
        ),
    ]
