# Generated by Django 5.1 on 2024-09-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0012_rename_catégorie_cours_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='cours_image',
            new_name='image',
        ),
    ]
