# Generated by Django 5.1 on 2024-09-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_chapitre_duree_leçon_duree_alter_chapitre_cours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursutilisateur',
            name='statut',
            field=models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('dropped', 'Abandonné')], default='active', max_length=25),
        ),
        migrations.CreateModel(
            name='ProgressionLeçon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_leçon', models.CharField(choices=[('not_started', 'Non commencée'), ('in_progress', 'En cours'), ('completed', 'Terminée')], default='not_started', max_length=20)),
                ('date_terminée', models.DateTimeField(blank=True, null=True)),
                ('cours_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='cours.coursutilisateur')),
                ('leçon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.leçon')),
            ],
        ),
    ]
