# Generated by Django 5.1 on 2024-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_groups_utilisateur_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassadeur',
            name='dernier_accès',
        ),
        migrations.RemoveField(
            model_name='ambassadeur',
            name='statut',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='dernier_accès',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(default='actif', max_length=50),
        ),
    ]
