# Generated by Django 5.1 on 2024-08-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_ambassadeur_dernier_accès_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
