# Generated by Django 5.1 on 2024-08-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_cours_image_alter_cours_auteur'),
        ('forum', '0002_alter_messageforum_auteur_alter_sujetforum_auteur'),
        ('messagerie', '0002_alter_message_destinataire_alter_message_expéditeur'),
        ('progressions', '0002_alter_progression_ambassadeur'),
        ('utilisateurs', '0004_utilisateur_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassadeur',
            name='utilisateur_ptr',
        ),
        migrations.RemoveField(
            model_name='ambassadeur',
            name='équipe',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('ambassadeur', 'Ambassadeur'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20),
        ),
        migrations.DeleteModel(
            name='Administrateur',
        ),
        migrations.DeleteModel(
            name='Ambassadeur',
        ),
    ]
