# Generated by Django 5.1 on 2024-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_remove_ambassadeur_utilisateur_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
