# Generated by Django 5.1 on 2024-08-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_utilisateur_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('ambassadeur', 'Ambassadeur'), ('utilisateur', 'Utilisateur'), ('team_leader', 'Leader')], default='utilisateur', max_length=20),
        ),
    ]
