# Generated by Django 5.1 on 2024-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_auto_20240918_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('ambassadeur', 'Ambassadeur'), ('team_leader', 'Leader')], default='ambassadeur', max_length=20),
        ),
    ]
