# Generated by Django 5.1 on 2024-08-30 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageforum',
            name='auteur',
            field=models.ForeignKey(limit_choices_to={'role': 'administrateur, team_leader'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sujetforum',
            name='auteur',
            field=models.ForeignKey(limit_choices_to={'role': 'administrateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to=settings.AUTH_USER_MODEL),
        ),
    ]
