# Generated by Django 5.1 on 2024-08-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
        ('utilisateurs', '0003_remove_ambassadeur_dernier_accès_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Équipe',
            new_name='Equipe',
        ),
    ]
