# Generated by Django 5.1 on 2024-08-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataire', to='utilisateurs.ambassadeur')),
                ('expéditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expéditeur', to='utilisateurs.ambassadeur')),
            ],
        ),
    ]
